apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-manual-scaling-deployment
spec:
  replicas: 3 # manual scaling
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: saiddinarfadilah/hello-world:spring
          env:
            - name: DB_HOST
              value: mysql-service.default.svc.cluster.local
            - name: DB_USERNAME
              value: admin
            - name: DB_PASSWORD
              value: admin
          resources:
            limits:
              cpu: 250m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-manual-scaling-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
